/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllocationsRouteImport } from './routes/allocations'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as ApiDisastersLiveRouteImport } from './routes/api/disasters/live'
import { Route as ApiPublicHooksIngestNdmaRouteImport } from './routes/api/public/hooks/ingest-ndma'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationsRoute = AllocationsRouteImport.update({
  id: '/allocations',
  path: '/allocations',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisastersLiveRoute = ApiDisastersLiveRouteImport.update({
  id: '/api/disasters/live',
  path: '/api/disasters/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIngestNdmaRoute =
  ApiPublicHooksIngestNdmaRouteImport.update({
    id: '/api/public/hooks/ingest-ndma',
    path: '/api/public/hooks/ingest-ndma',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allocations': typeof AllocationsRoute
  '/monitoring': typeof MonitoringRoute
  '/resources': typeof ResourcesRoute
  '/simulation': typeof SimulationRoute
  '/api/disasters/live': typeof ApiDisastersLiveRoute
  '/api/public/hooks/ingest-ndma': typeof ApiPublicHooksIngestNdmaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allocations': typeof AllocationsRoute
  '/monitoring': typeof MonitoringRoute
  '/resources': typeof ResourcesRoute
  '/simulation': typeof SimulationRoute
  '/api/disasters/live': typeof ApiDisastersLiveRoute
  '/api/public/hooks/ingest-ndma': typeof ApiPublicHooksIngestNdmaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allocations': typeof AllocationsRoute
  '/monitoring': typeof MonitoringRoute
  '/resources': typeof ResourcesRoute
  '/simulation': typeof SimulationRoute
  '/api/disasters/live': typeof ApiDisastersLiveRoute
  '/api/public/hooks/ingest-ndma': typeof ApiPublicHooksIngestNdmaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allocations'
    | '/monitoring'
    | '/resources'
    | '/simulation'
    | '/api/disasters/live'
    | '/api/public/hooks/ingest-ndma'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allocations'
    | '/monitoring'
    | '/resources'
    | '/simulation'
    | '/api/disasters/live'
    | '/api/public/hooks/ingest-ndma'
  id:
    | '__root__'
    | '/'
    | '/allocations'
    | '/monitoring'
    | '/resources'
    | '/simulation'
    | '/api/disasters/live'
    | '/api/public/hooks/ingest-ndma'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllocationsRoute: typeof AllocationsRoute
  MonitoringRoute: typeof MonitoringRoute
  ResourcesRoute: typeof ResourcesRoute
  SimulationRoute: typeof SimulationRoute
  ApiDisastersLiveRoute: typeof ApiDisastersLiveRoute
  ApiPublicHooksIngestNdmaRoute: typeof ApiPublicHooksIngestNdmaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocations': {
      id: '/allocations'
      path: '/allocations'
      fullPath: '/allocations'
      preLoaderRoute: typeof AllocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/disasters/live': {
      id: '/api/disasters/live'
      path: '/api/disasters/live'
      fullPath: '/api/disasters/live'
      preLoaderRoute: typeof ApiDisastersLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-ndma': {
      id: '/api/public/hooks/ingest-ndma'
      path: '/api/public/hooks/ingest-ndma'
      fullPath: '/api/public/hooks/ingest-ndma'
      preLoaderRoute: typeof ApiPublicHooksIngestNdmaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllocationsRoute: AllocationsRoute,
  MonitoringRoute: MonitoringRoute,
  ResourcesRoute: ResourcesRoute,
  SimulationRoute: SimulationRoute,
  ApiDisastersLiveRoute: ApiDisastersLiveRoute,
  ApiPublicHooksIngestNdmaRoute: ApiPublicHooksIngestNdmaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
